import theme from "styles/theme";

export const paletteList = [
  { label: "Primary Light", color: theme.palette.primary.light },
  { label: "Primary Main", color: theme.palette.primary.main },
  { label: "Primary Dark", color: theme.palette.primary.dark },
  { label: "Secondary Light", color: theme.palette.secondary.light },
  { label: "Secondary Main", color: theme.palette.secondary.main },
  { label: "Secondary Dark", color: theme.palette.secondary.dark },
  { label: "Error Light", color: theme.palette.error.light },
  { label: "Error Main", color: theme.palette.error.main },
  { label: "Error Dark", color: theme.palette.error.dark },
  { label: "Warning Light", color: theme.palette.warning.light },
  { label: "Warning Main", color: theme.palette.warning.main },
  { label: "Warning Dark", color: theme.palette.warning.dark },
  { label: "Info Light", color: theme.palette.info.light },
  { label: "Info Main", color: theme.palette.info.main },
  { label: "Info Dark", color: theme.palette.info.dark },
  { label: "Success Light", color: theme.palette.success.light },
  { label: "Success Main", color: theme.palette.success.main },
  { label: "Success Dark", color: theme.palette.success.dark },
  { label: "Grey 100", color: theme.palette.grey[100] },
  { label: "Grey 200", color: theme.palette.grey[200] },
  { label: "Grey 300", color: theme.palette.grey[300] },
  { label: "Grey 400", color: theme.palette.grey[400] },
  { label: "Grey 500", color: theme.palette.grey[500] },
  { label: "Grey 600", color: theme.palette.grey[600] },
  { label: "Grey 700", color: theme.palette.grey[700] },
  { label: "Grey 800", color: theme.palette.grey[800] },
  { label: "Grey 900", color: theme.palette.grey[900] },
  { label: "Shades 0o0", color: theme.palette.shades[0o0] },
  { label: "Shades 100", color: theme.palette.shades[100] },
  { label: "Shades 200", color: theme.palette.shades[200] },
  { label: "Shades 300", color: theme.palette.shades[300] },
  { label: "Shades 400", color: theme.palette.shades[400] },
  { label: "Shades 500", color: theme.palette.shades[500] },
  { label: "Shades 600", color: theme.palette.shades[600] },
  { label: "Shades 700", color: theme.palette.shades[700] },
  { label: "Shades 800", color: theme.palette.shades[800] },
  { label: "Shades 900", color: theme.palette.shades[900] },
  { label: "Shades fff", color: theme.palette.shades["fff"] },
];
