import DeleteIcon from "@mui/icons-material/Delete";
import SendIcon from "@mui/icons-material/Send";

export const buttonList = [
  { label: "Button 1", variant: "contained", color: "success", size: "small" },
  { label: "Button 1", variant: "contained", color: "success", size: "medium" },
  { label: "Button 1", variant: "contained", color: "success", size: "large" },
  {
    label: "Button 1",
    variant: "contained",
    color: "success",
    size: "small",
    hasIcon: true,
    iconPos: "start",
    icon: <DeleteIcon />,
  },
  {
    label: "Button 1",
    variant: "contained",
    color: "success",
    size: "medium",
    hasIcon: true,
    iconPos: "end",
    icon: <SendIcon />,
  },
  {
    label: "Button 1",
    variant: "contained",
    color: "success",
    size: "large",
    isUploadBtn: true,
    uploadType: <input hidden accept="image/*" multiple type="file" />,
  },
  {
    label: "Button 1",
    variant: "contained",
    color: "success",
    size: "large",
    loader: true,
  },
  {
    label: "Button 1",
    variant: "contained",
    color: "success",
    size: "large",
    disabled: true,
  },
  { label: "Button 1", variant: "contained", color: "error", size: "small" },
  { label: "Button 1", variant: "contained", color: "error", size: "medium" },
  { label: "Button 1", variant: "contained", color: "error", size: "large" },
  {
    label: "Button 1",
    variant: "contained",
    color: "error",
    size: "small",
    hasIcon: true,
    iconPos: "start",
    icon: <DeleteIcon />,
  },
  {
    label: "Button 1",
    variant: "contained",
    color: "error",
    size: "medium",
    hasIcon: true,
    iconPos: "end",
    icon: <SendIcon />,
  },
  {
    label: "Button 1",
    variant: "contained",
    color: "error",
    size: "large",
    isUploadBtn: true,
    uploadType: <input hidden accept="image/*" multiple type="file" />,
  },
  {
    label: "Button 1",
    variant: "contained",
    color: "error",
    size: "large",
    loader: true,
  },
  {
    label: "Button 1",
    variant: "contained",
    color: "error",
    size: "large",
    disabled: true,
  },
  { label: "Button 1", variant: "contained", color: "primary", size: "small" },
  { label: "Button 1", variant: "contained", color: "primary", size: "medium" },
  { label: "Button 1", variant: "contained", color: "primary", size: "large" },
  {
    label: "Button 1",
    variant: "contained",
    color: "primary",
    size: "small",
    hasIcon: true,
    iconPos: "start",
    icon: <DeleteIcon />,
  },
  {
    label: "Button 1",
    variant: "contained",
    color: "primary",
    size: "medium",
    hasIcon: true,
    iconPos: "end",
    icon: <SendIcon />,
  },
  {
    label: "Button 1",
    variant: "contained",
    color: "primary",
    size: "large",
    isUploadBtn: true,
    uploadType: <input hidden accept="image/*" multiple type="file" />,
  },
  {
    label: "Button 1",
    variant: "contained",
    color: "primary",
    size: "large",
    loader: true,
  },
  {
    label: "Button 1",
    variant: "contained",
    color: "primary",
    size: "large",
    disabled: true,
  },
  {
    label: "Button 1",
    variant: "contained",
    color: "secondary",
    size: "small",
  },
  {
    label: "Button 1",
    variant: "contained",
    color: "secondary",
    size: "medium",
  },
  {
    label: "Button 1",
    variant: "contained",
    color: "secondary",
    size: "large",
  },
  {
    label: "Button 1",
    variant: "contained",
    color: "secondary",
    size: "small",
    hasIcon: true,
    iconPos: "start",
    icon: <DeleteIcon />,
  },
  {
    label: "Button 1",
    variant: "contained",
    color: "secondary",
    size: "medium",
    hasIcon: true,
    iconPos: "end",
    icon: <SendIcon />,
  },
  {
    label: "Button 1",
    variant: "contained",
    color: "secondary",
    size: "large",
    isUploadBtn: true,
    uploadType: <input hidden accept="image/*" multiple type="file" />,
  },
  {
    label: "Button 1",
    variant: "contained",
    color: "secondary",
    size: "large",
    loader: true,
  },
  {
    label: "Button 1",
    variant: "contained",
    color: "secondary",
    size: "large",
    disabled: true,
  },
  { label: "Button 1", variant: "outlined", color: "success", size: "small" },
  { label: "Button 1", variant: "outlined", color: "success", size: "medium" },
  { label: "Button 1", variant: "outlined", color: "success", size: "large" },
  {
    label: "Button 1",
    variant: "outlined",
    color: "success",
    size: "small",
    hasIcon: true,
    iconPos: "start",
    icon: <DeleteIcon />,
  },
  {
    label: "Button 1",
    variant: "outlined",
    color: "success",
    size: "medium",
    hasIcon: true,
    iconPos: "end",
    icon: <SendIcon />,
  },
  {
    label: "Button 1",
    variant: "outlined",
    color: "success",
    size: "large",
    isUploadBtn: true,
    uploadType: <input hidden accept="image/*" multiple type="file" />,
  },
  {
    label: "Button 1",
    variant: "outlined",
    color: "success",
    size: "large",
    loader: true,
  },
  {
    label: "Button 1",
    variant: "outlined",
    color: "success",
    size: "large",
    disabled: true,
  },
  { label: "Button 1", variant: "outlined", color: "error", size: "small" },
  { label: "Button 1", variant: "outlined", color: "error", size: "medium" },
  { label: "Button 1", variant: "outlined", color: "error", size: "large" },
  {
    label: "Button 1",
    variant: "outlined",
    color: "error",
    size: "small",
    hasIcon: true,
    iconPos: "start",
    icon: <DeleteIcon />,
  },
  {
    label: "Button 1",
    variant: "outlined",
    color: "error",
    size: "medium",
    hasIcon: true,
    iconPos: "end",
    icon: <SendIcon />,
  },
  {
    label: "Button 1",
    variant: "outlined",
    color: "error",
    size: "large",
    isUploadBtn: true,
    uploadType: <input hidden accept="image/*" multiple type="file" />,
  },
  {
    label: "Button 1",
    variant: "outlined",
    color: "error",
    size: "large",
    loader: true,
  },
  {
    label: "Button 1",
    variant: "outlined",
    color: "error",
    size: "large",
    disabled: true,
  },
  { label: "Button 1", variant: "outlined", color: "primary", size: "small" },
  { label: "Button 1", variant: "outlined", color: "primary", size: "medium" },
  { label: "Button 1", variant: "outlined", color: "primary", size: "large" },
  {
    label: "Button 1",
    variant: "outlined",
    color: "primary",
    size: "small",
    hasIcon: true,
    iconPos: "start",
    icon: <DeleteIcon />,
  },
  {
    label: "Button 1",
    variant: "outlined",
    color: "primary",
    size: "medium",
    hasIcon: true,
    iconPos: "end",
    icon: <SendIcon />,
  },
  {
    label: "Button 1",
    variant: "outlined",
    color: "primary",
    size: "large",
    isUploadBtn: true,
    uploadType: <input hidden accept="image/*" multiple type="file" />,
  },
  {
    label: "Button 1",
    variant: "outlined",
    color: "primary",
    size: "large",
    loader: true,
  },
  {
    label: "Button 1",
    variant: "outlined",
    color: "primary",
    size: "large",
    disabled: true,
  },
  {
    label: "Button 1",
    variant: "outlined",
    color: "secondary",
    size: "small",
  },
  {
    label: "Button 1",
    variant: "outlined",
    color: "secondary",
    size: "medium",
  },
  {
    label: "Button 1",
    variant: "outlined",
    color: "secondary",
    size: "large",
  },
  {
    label: "Button 1",
    variant: "outlined",
    color: "secondary",
    size: "small",
    hasIcon: true,
    iconPos: "start",
    icon: <DeleteIcon />,
  },
  {
    label: "Button 1",
    variant: "outlined",
    color: "secondary",
    size: "medium",
    hasIcon: true,
    iconPos: "end",
    icon: <SendIcon />,
  },
  {
    label: "Button 1",
    variant: "outlined",
    color: "secondary",
    size: "large",
    isUploadBtn: true,
    uploadType: <input hidden accept="image/*" multiple type="file" />,
  },
  {
    label: "Button 1",
    variant: "outlined",
    color: "secondary",
    size: "large",
    loader: true,
  },
  {
    label: "Button 1",
    variant: "outlined",
    color: "secondary",
    size: "large",
    disabled: true,
  },
];
